### ISSUE TITLE
128を超えるJavaScriptがある場合にリクエストを複数同時に処理するとscriptCacheが壊れる

### ISSUE THREAD

**Issue by nobeans** [seasarorg/mayaa#14]
現状だとコンパイル済みスクリプトのキャッシュのキャパシティが↓で`128`とハードコードされています。
https://github.com/seasarorg/mayaa/blob/master/src-impl/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentImpl.java#L52

128個を超えるスクリプトが存在していて、すでにキャッシュに128個分のコンパイル済みスクリプトが格納されている状態で、キャッシュに存在しないスクリプトのコンパイルリクエストがきた場合、
https://github.com/seasarorg/mayaa/blob/master/src-impl/org/seasar/mayaa/impl/util/WeakValueHashMap.java#L68-L71
でキャッシュのlastを`LinkedList#removeLast()`で刈り取る実装になっています。

しかし、
https://github.com/seasarorg/mayaa/blob/master/src-impl/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentImpl.java#L70-L73
でダブルチェックロック的にキャッシュからの引当を **同期なし** に実行しているため、`LinkedList#removeLast()`が同期なしで複数スレッドから同時実行される可能性があります。

複数スレッドから同時に実行された場合、`LinkedList`の内部データが破壊されてしまい、毎回(要素が存在していたとしても)`LinkedList#removeLast()`で`NoSuchElementException`が発生することになります。

**Comment by nobeans** [comment]
Groovyで書いた模擬コードですが、壊れ具合を再現できます。

```
import java.util.concurrent.CountDownLatch
import java.util.concurrent.atomic.AtomicBoolean

final cacheSize = 128  // Mayaaの実装と同じ
final threadsCount = 200
final trialCount = 100

def lock = new Object()
def foundNSEE = new AtomicBoolean(false)
def l = new LinkedList()

for (int trialId = 0; trialId < trialCount && !foundNSEE.get(); trialId++) {
    def latch = new CountDownLatch(threadsCount)
    threads = (1..threadsCount).collect { requestId ->
        def id = "[$trialId]$requestId"
        Thread.start {
            try {
                // 一斉に動いた方がぶつかりやすいので待ち合わせる
                latch.countDown()
                latch.await()

                synchronized (lock) {
                    l.addFirst("ITEM:$id") // addFirstは同期的にしか実行されないため、同じように同期化する
                }
                if (l.size() > cacheSize) {
                    l.removeLast() // これが複数同時に実行された場合、が問題
                }
            } catch (NoSuchElementException e) {
                println id
                e.printStackTrace()
                foundNSEE.set(true)
            }
        }
    }
    threads*.join()
}

if (!foundNSEE.get()) {
    println "Not reproduced (no error)."
    System.exit(0)
}

// (厳密には壊れ方にもよるが)1回でも発生すると、あとはなんどやってもエラーになる(場合がある)
def verifyTrialCount = 100
def nseeCount = 0
verifyTrialCount.times {
    l.addFirst("DUMMY")
    assert l.size() > 0
    try {
        l.removeLast()
    } catch (NoSuchElementException e) {
        nseeCount++
    }
}
if (nseeCount == verifyTrialCount) {
    println "Reproduced!"
} else {
    println "Not reproduced (error occurs but it works later)."
}
```

**Comment by mitonize** [comment]
@nobeans さんの再現コードを元に WeakValueHashMap 自体の再現のためのJUnitを追加しました。
mitonize/issue14 ブランチをチェックアウトして `mvn test` で実行できます。
手元の環境ではスレッド数を減らしても比較的高い確率で再現しましたのでスレッド数10、試行回数200としています。
なお、運良く再現しなかった場合は test が通ってしまいます…

**Comment by mitonize** [comment]
なお、`hardCache` をJava7から使用できる `ConcurrentLinkedDeque`クラスに変更するだけで解消します。
```diff
-    private final LinkedList hardCache = new LinkedList();
+    private final ConcurrentLinkedDeque hardCache = new ConcurrentLinkedDeque();
```
