### ISSUE TITLE
[feature-request] ScriptEnvironmentImplでのスクリプトキャッシュの容量を設定として指定したい

### ISSUE THREAD

**Issue by nobeans** [seasarorg/mayaa#15]
スクリプト数が128を超える場合にキャッシュを有効に利用できるように、任意の数字を指定できると嬉しいです。

https://github.com/seasarorg/mayaa/blob/master/src-impl/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentImpl.java#L52

**Comment by mitonize** [comment]
org.seasar.mayaa.provider.ServiceProvider にて cacheSize というパラメータ名で指定できるようにするのはいかがでしょうか。
デフォルトは128のままとし、追加で配置する org.seasar.mayaa.provider.ServiceProviderにて指定するイメージです。

org.seasar.mayaa.provider.ServiceProvider
```xml
<scriptEnvironment class="org.seasar.mayaa.impl.cycle.script.rhino.ScriptEnvironmentImpl">
    <scope class="org.seasar.mayaa.impl.cycle.scope.ParamScope"/>
    <scope class="org.seasar.mayaa.impl.cycle.scope.HeaderScope"/>
    <scope class="org.seasar.mayaa.impl.cycle.scope.BindingScope"/>

    <parameter name="wrapFactory" value="org.seasar.mayaa.impl.cycle.script.rhino.WrapFactoryImpl"/>
    <parameter name="cacheSize" value="128"/>  <!-- キャッシュのサイズを指定 -->
</scriptEnvironment>
```

**Comment by nobeans** [comment]
いいですね。利用側で指定可能であればOKなので、ご提案の対処で十分だと思います。

**Comment by mitonize** [comment]
ご確認ありがとうございます。
